### ISSUE TITLE
membrane_core branch develop does not exist

### ISSUE THREAD

**Issue by peacememories** [membraneframework/membrane_webrtc_plugin#23]
Hi, and thanks for developing this very interesting framework.
I have been trying to test `membrane_webrtc_plugin`, but for now I am stuck at including it as a dependency. The first problem I have is that the library depends on `membrane_core` on the branch `develop`, which does not seem to exist.

Overriding the dependency in my project leads to further errors, I gave up when `membrane_funnel_plugin` reported that `Pad.ref` was not allowed in pattern matches, which *does* work when just checking out that repository 😅

I'm pretty new to Elixir, so I don't know the best way forward here

**Comment by peacememories** [comment]
Okay, it seems like the reason this "works" when checking out the repository is that the correct commit is still mentioned in the `mix.lock`. If i copy that line to my lock file I get the same errors I was getting when overriding the dependency completely.
So the immediate solution would be to change the branch in the `mix.exs` file to master, if that version is code-compatible.

**Comment by mickel8** [comment]
Yes, mix.lock saves commit number that was used while including dependency. I think we will update it soon but as you wrote you can use membrane_core from master branch :wink:

**Comment by peacememories** [comment]
For now i basically copied the lockfile entries to my project and did some fixing until it compiled^^
As you said, it's enough for now, but I'm looking forward to the update :)
Now on to actually getting the hang of membrane 😅
